// Vite plugin that writes sw.js, the service worker that lets the installed app run offline.
// It lists every file of the build so the first visit caches the whole app, and names the
// cache after a hash of those names, so each new build replaces the old cache.

import { createHash } from 'node:crypto';
import { readdirSync } from 'node:fs';
import type { Plugin } from 'vite';

export function serviceWorker(): Plugin {
  return {
    name: 'poker-coach-sw',
    apply: 'build',
    generateBundle(_, bundle) {
      const files = [
        './',
        ...Object.keys(bundle).filter((f) => f !== 'sw.js'),
        ...readdirSync(new URL('../public', import.meta.url)),
      ].sort();
      const version = createHash('sha256').update(files.join('\n')).digest('hex').slice(0, 12);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(files, version) });
    },
  };
}

function swSource(files: string[], version: string): string {
  return `// Generated by scripts/sw-plugin.ts at build time.
const CACHE = 'poker-coach-${version}';
const FILES = ${JSON.stringify(files)};
// Fonts come from Google Fonts; they are cached the first time they load.
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('poker-coach-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const own = url.origin === self.location.origin;
  if (!own && !FONT_HOSTS.includes(url.hostname)) return; // the Claude API and anything else go to the network
  if (req.mode === 'navigate') {
    // Pages: the network first so a new build shows up, the cached app when offline.
    e.respondWith(fetch(req).catch(() => caches.match('./', { ignoreSearch: true })));
    return;
  }
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok || res.type === 'opaque') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    })),
  );
});
`;
}
